routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\StockEmail;
use Illuminate\Support\Facades\Mail;

Route::get('/', 'HomeController@index')->name('home');


Auth::routes();


Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
   Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
   Route::resource('kategori', 'KategoriController');

   Route::get('bahan_baku/data', 'BahanBakuController@listData')->name('bahan_baku.data');
   Route::post('bahan_baku/hapus', 'BahanBakuController@deleteSelected');
   Route::resource('bahan_baku', 'BahanBakuController');
   Route::get('bahan_baku/lbahanbaku', 'BahanBakuController@show');

   Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
   Route::resource('supplier', 'SupplierController');

   Route::get('karyawan/data', 'KaryawanController@listData')->name('karyawan.data');
   Route::resource('karyawan', 'KaryawanController');

   Route::get('jenis_pengeluaran/data', 'JenisPengeluaranController@listData')->name('jenis_pengeluaran.data');
   Route::resource('jenis_pengeluaran', 'JenisPengeluaranController');

   Route::get('pembelian/data', 'PembelianController@listData')->name('pembelian.data');
   Route::get('pembelian/{id}/tambah', 'PembelianController@create');
   Route::get('pembelian/{id}/lihat', 'PembelianController@show');
   Route::resource('pembelian', 'PembelianController');

   Route::get('dpembelian/{id}/data', 'DPembelianController@listData')->name('dpembelian.data');
   Route::get('dpembelian/loadform/{diskon}/{total}', 'DPembelianController@loadForm');
   Route::resource('dpembelian', 'DPembelianController'); 

   Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
   Route::get('pengeluaran/{id}/tambah', 'PengeluaranController@create');
   Route::get('pengeluaran/{id}/lihat', 'PengeluaranController@show');
   Route::resource('pengeluaran', 'PengeluaranController');

   Route::get('dpengeluaran/{id}/data', 'DPengeluaranController@listData')->name('dpengeluaran.data');
   Route::get('dpengeluaran/loadform/{total}', 'DPengeluaranController@loadForm');
   Route::resource('dpengeluaran', 'DPengeluaranController'); 

   Route::get('pemakaian/data', 'PemakaianController@listData')->name('pemakaian.data');
   Route::get('pemakaian/{id}/tambah', 'PemakaianController@create');
   Route::get('pemakaian/{id}/lihat', 'PemakaianController@show');
   Route::resource('pemakaian', 'PemakaianController');

   Route::get('dpemakaian/{id}/data', 'DPemakaianController@listData')->name('dpemakaian.data');
   Route::get('dpemakaian/loadform/{total}', 'DPemakaianController@loadForm');
   Route::resource('dpemakaian', 'DPemakaianController'); 

   Route::get('laporan', 'LaporanController@index')->name('laporan.index');
   Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
   Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data'); 
   Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

   Route::get('lpembelian', 'LPembelianController@index')->name('lpembelian.index');
   Route::post('lpembelian', 'LPembelianController@refresh')->name('lpembelian.refresh');
   Route::get('lpembelian/data/{awal}/{akhir}', 'LPembelianController@listData')->name('lpembelian.data'); 
   Route::get('lpembelian/pdf/{awal}/{akhir}', 'LPembelianController@exportPDF');

   Route::get('lpengeluaran', 'LPengeluaranController@index')->name('lpengeluaran.index');
   Route::post('lpengeluaran', 'LPengeluaranController@refresh')->name('lpengeluaran.refresh');
   Route::get('lpengeluaran/data/{awal}/{akhir}', 'LPengeluaranController@listData')->name('lpengeluaran.data'); 
   Route::get('lpengeluaran/pdf/{awal}/{akhir}', 'LPengeluaranController@exportPDF');

   Route::get('lpemakaian', 'LPemakaianController@index')->name('lpemakaian.index');
   Route::post('lpemakaian', 'LPemakaianController@refresh')->name('lpemakaian.refresh');
   Route::get('lpemakaian/data/{awal}/{akhir}', 'LPemakaianController@listData')->name('lpemakaian.data'); 
   Route::get('lpemakaian/pdf/{awal}/{akhir}', 'LPemakaianController@exportPDF');

   Route::get('user/data', 'UserController@listData')->name('user.data');
   Route::get('user/profil', 'UserController@profil')->name('user.profil');
   Route::patch('user/{id}/change', 'UserController@changeProfil');
   Route::resource('user', 'UserController');

   Route::resource('setting', 'SettingController');

   //email
   Route::get('/email', function() {
      return view('send_email');
   });

   Route::get('/kirimemail',function(){
      Mail::to('luluk.9456@students.amikom.ac.id')->send(new StockEmail());
   });

   Route::post('/sendEmail', 'Email@sendEmail');
});


Route::group(['middleware' => 'web'], function(){
   Route::get('user/profil', 'UserController@profil')->name('user.profil');
   Route::patch('user/{id}/change', 'UserController@changeProfil');

   Route::get('laporan', 'LaporanController@index')->name('laporan.index');
   Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
   Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data'); 
   Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

   Route::get('lpembelian', 'LPembelianController@index')->name('lpembelian.index');
   Route::post('lpembelian', 'LPembelianController@refresh')->name('lpembelian.refresh');
   Route::get('lpembelian/data/{awal}/{akhir}', 'LPembelianController@listData')->name('lpembelian.data'); 
   Route::get('lpembelian/pdf/{awal}/{akhir}', 'LPembelianController@exportPDF');

   Route::get('lpengeluaran', 'LPengeluaranController@index')->name('lpengeluaran.index');
   Route::post('lpengeluaran', 'LPengeluaranController@refresh')->name('lpengeluaran.refresh');
   Route::get('lpengeluaran/data/{awal}/{akhir}', 'LPengeluaranController@listData')->name('lpengeluaran.data'); 
   Route::get('lpengeluaran/pdf/{awal}/{akhir}', 'LPengeluaranController@exportPDF');

   Route::get('lpemakaian', 'LPemakaianController@index')->name('lpemakaian.index');
   Route::post('lpemakaian', 'LPemakaianController@refresh')->name('lpemakaian.refresh');
   Route::get('lpemakaian/data/{awal}/{akhir}', 'LPemakaianController@listData')->name('lpemakaian.data'); 
   Route::get('lpemakaian/pdf/{awal}/{akhir}', 'LPemakaianController@exportPDF');
});

app/Karyawan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Karyawan extends Model
{
    protected $table  	  = 'karyawan';
	protected $primaryKey = 'id_karyawan';

	public function pemakaian()
	{
    	return $this->hasMany('App\Pemakaian', 'id_supplier');
    }
}

app/Http/Controllers/KaryawanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Karyawan;

class KaryawanController extends Controller
{
    //Fungsi Utama
    public function index()
    {
        return view('karyawan.index'); 
    }

    //Fungsi yang akan dipanggil setelah index
    public function listData()
    {
        $karyawan   = Karyawan::orderBy('id_karyawan', 'desc')->get();
        $no         = 0;
        $data       = array();
        foreach($karyawan as $list)
        {
            $no ++;
            $row    = array();
            $row[]  = "<input type='checkbox' name='id[]'' value='".$list->id_karyawan."'>";
            $row[]  = $no;
            $row[]  = $list->kode_karyawan;
            $row[]  = $list->nama;
            $row[]  = $list->alamat;
            $row[]  = $list->telpon;
            $row[]  = '<div class="btn-group">
                       	<a onclick="editForm('.$list->id_karyawan.')" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                       	<a onclick="deleteData('.$list->id_karyawan.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                       </div>';
            $data[] = $row;
        }
        $output     = array("data" => $data);
        return response()->json($output);
    }

    public function store(Request $request)
    {
        $jml = Karyawan::where('kode_karyawan', '=', $request['kode'])->count();
        
        if($jml < 1)
        {
            $karyawan                   = new Karyawan;
            $karyawan->kode_karyawan    = $request['kode'];
            $karyawan->nama             = $request['nama'];
            $karyawan->alamat           = $request['alamat'];
            $karyawan->telpon           = $request['telpon'];
            $karyawan->save();
            echo json_encode(array('msg'=>'success'));
        }
        else
        {
            echo json_encode(array('msg'=>'error'));
        }
    }

    public function edit($id)
    {
        $karyawan = Karyawan::find($id);
        echo json_encode($karyawan);
    }

    public function update(Request $request, $id)
    {
        $karyawan                   = Karyawan::find($id);
        $karyawan->nama             = $request['nama'];
        $karyawan->alamat           = $request['alamat'];
        $karyawan->telpon           = $request['telpon'];
        $karyawan->update();
        echo json_encode(array('msg'=>'success'));
    }

    public function destroy($id)
    {
        $karyawan = Karyawan::find($id);
        $karyawan->delete();
    }
} 

resources/views/karyawan/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
         <form class="form-horizontal" data-toggle="validator" method="post">
         {{ csrf_field() }} {{ method_field('POST') }}
         
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
               <h3 class="modal-title"></h3>
            </div>
                     
            <div class="modal-body">            
               <input type="hidden" id="id" name="id">
               <div class="form-group">
                  <label for="kode" class="col-md-3 control-label">Kode Karyawan</label>
                  <div class="col-md-6">
                     <input id="kode" type="text" maxlength="20" class="form-control" name="kode" autofocus required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
               <div class="form-group">
                  <label for="nama" class="col-md-3 control-label">Nama Karyawan</label>
                  <div class="col-md-6">
                     <input id="nama" type="text" maxlength="30" class="form-control" name="nama" autofocus required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
               <div class="form-group">
                  <label for="alamat" class="col-md-3 control-label">Alamat</label>
                  <div class="col-md-8">
                     <input id="alamat" type="text" class="form-control" name="alamat" required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
               <div class="form-group">
                  <label for="telpon" class="col-md-3 control-label">Telpon</label>
                  <div class="col-md-6">
                     <input id="telpon" type="text" maxlength="12" onkeypress="return hanyaAngka(event, false)" class="form-control" name="telpon" autofocus required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
            </div>
            
            <div class="modal-footer">
               <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
               <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
            </div>
            
         </form>
      </div>
   </div>
</div>

<script language="javascript">
  function hanyaAngka(e, decimal) 
  {
    var key;
    var keychar;
    
    if(window.event) 
    {
      key   = window.event.keyCode;
    } 
    else if(e) 
    {
        key = e.which;
    } 
    else return true;
   
    keychar = String.fromCharCode(key);
    if( (key==null) || (key==0) || (key==8) ||  (key==9) || (key==13) || (key==27) ) 
    {
      return true;
    } 
    else if ( (("0123456789").indexOf(keychar) > -1) ) 
    {
      return true;
    } 
    else if(decimal && (keychar == ".")) 
    {
      return true;
    } 
    else return false;
  }
</script>

resources/views/karyawan/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Karyawan
@endsection

@section('breadcrumb')
  @parent
  <li>karyawan</li>
@endsection

@section('content')     
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
        </div>

        <div class="box-body"> 
          <form method="post" id="form-karyawan">
          {{ csrf_field() }}
            <table class="table table-striped">
              <thead>
                <tr>
                  <th width="20"><input type="checkbox" value="1" id="select-all"></th>
                  <th width="20">No</th>
                  <th>Kode Karyawan</th>
                  <th>Nama Karyawan</th>
                  <th>Alamat</th>
                  <th>Telpon</th>
                  <th width="100">Aksi</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </form>
        </div>

      </div>
    </div>
  </div>
  @include('karyawan.form')
@endsection

@section('script')
  <script type="text/javascript">
  var table, save_method;
  $(function(){

    //Menampilkan data dengan plugin DataTable
    table = $('.table').DataTable({
      "processing"  : true,
      "ajax"        : 
      {
        "url"       : "{{ route('karyawan.data') }}",
        "type"      : "GET"
      },
      'columnDefs'  :
      [{
        'targets'   : 0,
        'searchable': false,
        'orderable' : false
      }],
      'order'       : [1, 'asc']
    }); 

    $('#select-all').click(function(){
      $('input[type="checkbox"]').prop('checked', this.checked);
    });
     
    //Menyimpan data form tambah/edit beserta validasinya
    $('#modal-form form').on('submit', function(e){
      if(!e.isDefaultPrevented())
      {
        var id                       = $('#id').val();
        if(save_method == "add") url = "{{ route('karyawan.store') }}";
        else url                     = "karyawan/"+id;
           
          $.ajax({
            url      : url,
            type     : "POST",
            data     : $('#modal-form form').serialize(),
            dataType : 'JSON',
            success  : function(data)
            {
              if(data.msg=="error")
              {
                swal("Kode karyawan sudah digunakan!", "", "warning");
                $('#kode').focus().select();
              }
              else
              {
                swal("Karyawan Berhasil Disimpan!", "", "success");
                $('#modal-form').modal('hide');
                table.ajax.reload();
              }
            },
            error   : function()
            {
              swal("Tidak dapat menyimpan data!", "", "warning");
            }   
          });
        return false;
      }
    });
  });

  //Menampilkan form tambah
  function addForm()
  {
    save_method = "add";
    $('input[name=_method]').val('POST');
    $('#modal-form').modal('show');
    $('#modal-form form')[0].reset();            
    $('.modal-title').text('Tambah Karyawan');
    $('#kode').attr('readonly', false);
  }

  //Menampilkan form edit dan menampilkan data pada form tersebut
  function editForm(id)
  {
    save_method = "edit";
    $('input[name=_method]').val('PATCH');
    $('#modal-form form')[0].reset();
    $.ajax({
      url      : "karyawan/"+id+"/edit",
      type     : "GET",
      dataType : "JSON",
      success  : function(data)
      {
        $('#modal-form').modal('show');
        $('.modal-title').text('Edit Karyawan');
         
        $('#id').val(data.id_karyawan);
        $('#kode').val(data.kode_karyawan).attr('readonly', true);
        $('#nama').val(data.nama);
        $('#alamat').val(data.alamat);
        $('#telpon').val(data.telpon);
      },
      error   : function()
      {
        swal("Tidak dapat menampilkan data!", "", "warning");
      }
    });
  }

  //Menghapus Data
  function deleteData(id)
  {
    swal({
      title               : "Anda Yakin?",
      text                : "Hapus Karyawan?",
      icon                : "warning",
      showCancelButton    : true,
      confirmButtonColor  : "DD6B55",
      confirmButtonText   : "YA, Hapus",
      closeOnConfirm      : false
    }, 
    function(isConfirm)
    {
      if (!isConfirm) return;
      $.ajax({
        url   : "karyawan/"+id,
        type  : "POST",
        data  : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
        success: function (data) 
        {
          swal("Berhasil!", "Karyawan berhasil dihapus!", "success");
          table.ajax.reload();
        },
        error: function (xhr, ajaxOptions, thrownError) 
        {
          swal("Gagal Menghapus!", "Silahkan coba lagi!", "error");
        }
      });
    });
  }
  </script>
@endsection