routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\StockEmail;
use Illuminate\Support\Facades\Mail;

Route::get('/', 'HomeController@index')->name('home');


Auth::routes();


Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
   Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
   Route::resource('kategori', 'KategoriController');

   Route::get('bahan_baku/data', 'BahanBakuController@listData')->name('bahan_baku.data');
   Route::post('bahan_baku/hapus', 'BahanBakuController@deleteSelected');
   Route::resource('bahan_baku', 'BahanBakuController');
   Route::get('bahan_baku/lbahanbaku', 'BahanBakuController@show');

   Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
   Route::resource('supplier', 'SupplierController');

   Route::get('karyawan/data', 'KaryawanController@listData')->name('karyawan.data');
   Route::resource('karyawan', 'KaryawanController');

   Route::get('jenis_pengeluaran/data', 'JenisPengeluaranController@listData')->name('jenis_pengeluaran.data');
   Route::resource('jenis_pengeluaran', 'JenisPengeluaranController');

   Route::get('pembelian/data', 'PembelianController@listData')->name('pembelian.data');
   Route::get('pembelian/{id}/tambah', 'PembelianController@create');
   Route::get('pembelian/{id}/lihat', 'PembelianController@show');
   Route::resource('pembelian', 'PembelianController');

   Route::get('dpembelian/{id}/data', 'DPembelianController@listData')->name('dpembelian.data');
   Route::get('dpembelian/loadform/{diskon}/{total}', 'DPembelianController@loadForm');
   Route::resource('dpembelian', 'DPembelianController'); 

   Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
   Route::get('pengeluaran/{id}/tambah', 'PengeluaranController@create');
   Route::get('pengeluaran/{id}/lihat', 'PengeluaranController@show');
   Route::resource('pengeluaran', 'PengeluaranController');

   Route::get('dpengeluaran/{id}/data', 'DPengeluaranController@listData')->name('dpengeluaran.data');
   Route::get('dpengeluaran/loadform/{total}', 'DPengeluaranController@loadForm');
   Route::resource('dpengeluaran', 'DPengeluaranController'); 

   Route::get('pemakaian/data', 'PemakaianController@listData')->name('pemakaian.data');
   Route::get('pemakaian/{id}/tambah', 'PemakaianController@create');
   Route::get('pemakaian/{id}/lihat', 'PemakaianController@show');
   Route::resource('pemakaian', 'PemakaianController');

   Route::get('dpemakaian/{id}/data', 'DPemakaianController@listData')->name('dpemakaian.data');
   Route::get('dpemakaian/loadform/{total}', 'DPemakaianController@loadForm');
   Route::resource('dpemakaian', 'DPemakaianController'); 

   Route::get('laporan', 'LaporanController@index')->name('laporan.index');
   Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
   Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data'); 
   Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

   Route::get('lpembelian', 'LPembelianController@index')->name('lpembelian.index');
   Route::post('lpembelian', 'LPembelianController@refresh')->name('lpembelian.refresh');
   Route::get('lpembelian/data/{awal}/{akhir}', 'LPembelianController@listData')->name('lpembelian.data'); 
   Route::get('lpembelian/pdf/{awal}/{akhir}', 'LPembelianController@exportPDF');

   Route::get('lpengeluaran', 'LPengeluaranController@index')->name('lpengeluaran.index');
   Route::post('lpengeluaran', 'LPengeluaranController@refresh')->name('lpengeluaran.refresh');
   Route::get('lpengeluaran/data/{awal}/{akhir}', 'LPengeluaranController@listData')->name('lpengeluaran.data'); 
   Route::get('lpengeluaran/pdf/{awal}/{akhir}', 'LPengeluaranController@exportPDF');

   Route::get('lpemakaian', 'LPemakaianController@index')->name('lpemakaian.index');
   Route::post('lpemakaian', 'LPemakaianController@refresh')->name('lpemakaian.refresh');
   Route::get('lpemakaian/data/{awal}/{akhir}', 'LPemakaianController@listData')->name('lpemakaian.data'); 
   Route::get('lpemakaian/pdf/{awal}/{akhir}', 'LPemakaianController@exportPDF');

   Route::get('user/data', 'UserController@listData')->name('user.data');
   Route::get('user/profil', 'UserController@profil')->name('user.profil');
   Route::patch('user/{id}/change', 'UserController@changeProfil');
   Route::resource('user', 'UserController');

   Route::resource('setting', 'SettingController');

   //email
   Route::get('/email', function() {
      return view('send_email');
   });

   Route::get('/kirimemail',function(){
      Mail::to('luluk.9456@students.amikom.ac.id')->send(new StockEmail());
   });

   Route::post('/sendEmail', 'Email@sendEmail');
});


Route::group(['middleware' => 'web'], function(){
   Route::get('user/profil', 'UserController@profil')->name('user.profil');
   Route::patch('user/{id}/change', 'UserController@changeProfil');

   Route::get('laporan', 'LaporanController@index')->name('laporan.index');
   Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
   Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data'); 
   Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

   Route::get('lpembelian', 'LPembelianController@index')->name('lpembelian.index');
   Route::post('lpembelian', 'LPembelianController@refresh')->name('lpembelian.refresh');
   Route::get('lpembelian/data/{awal}/{akhir}', 'LPembelianController@listData')->name('lpembelian.data'); 
   Route::get('lpembelian/pdf/{awal}/{akhir}', 'LPembelianController@exportPDF');

   Route::get('lpengeluaran', 'LPengeluaranController@index')->name('lpengeluaran.index');
   Route::post('lpengeluaran', 'LPengeluaranController@refresh')->name('lpengeluaran.refresh');
   Route::get('lpengeluaran/data/{awal}/{akhir}', 'LPengeluaranController@listData')->name('lpengeluaran.data'); 
   Route::get('lpengeluaran/pdf/{awal}/{akhir}', 'LPengeluaranController@exportPDF');

   Route::get('lpemakaian', 'LPemakaianController@index')->name('lpemakaian.index');
   Route::post('lpemakaian', 'LPemakaianController@refresh')->name('lpemakaian.refresh');
   Route::get('lpemakaian/data/{awal}/{akhir}', 'LPemakaianController@listData')->name('lpemakaian.data'); 
   Route::get('lpemakaian/pdf/{awal}/{akhir}', 'LPemakaianController@exportPDF');
});

app/DPemakaian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DPemakaian extends Model
{
	protected $table 	  = 'dpemakaian';
	protected $primaryKey = 'id_dpemakaian';
}

app/Http/Controllers/DPemakaianController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Redirect;
use Auth;
use PDF;
use App\Pemakaian;
use App\DPemakaian;
use App\BahanBaku;
use App\Karyawan;

class DPemakaianController extends Controller
{
  //Fungsi Utama
	public function index()
	{
    $bahan_baku  = BahanBaku::all();
    $idpemakaian = session('idpemakaian');
    $karyawan    = Karyawan::find(session('idkaryawan'));
    return view('dpemakaian.index', compact('bahan_baku', 'idpemakaian', 'karyawan'));
  }

  //Fungsi yang akan dipanggil setelah index dgn parameter id yang akan dipanggil datanya
  public function listData($id)
  {
    $detail 	    = DPemakaian::leftJoin('bahan_baku', 'bahan_baku.kode_bahan_baku', '=', 'dpemakaian.kode_bahan_baku')
    ->where('id_pemakaian', '=', $id)
    ->get();
    $no 		      = 0;
    $data 		    = array();
    $total        = 0;
    $total_item   = 0;
    foreach($detail as $list)
    {
      $no ++;
      $row 	  = array();
      $row[] 	= $no;
      $row[] 	= $list->kode_bahan_baku;
      $row[] 	= $list->nama_bahan_baku;
      $row[] 	= "Rp. ".format_uang($list->harga_beli);
      $row[] 	= "<input type='number' class='form-control' name='jumlah_$list->id_dpemakaian' value='$list->jumlah' min='1' max='$list->stok' onChange='changeCount($list->id_dpemakaian)'>";
      $row[] 	= "Rp. ".format_uang($list->harga_beli * $list->jumlah);
      $row[] 	= '<a onclick="deleteItem('.$list->id_dpemakaian.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>';
      //Baris untuk menyimpan perhitungan
      $data[] = $row;

      $total        += $list->harga_beli * $list->jumlah;
      $total_item   += $list->jumlah;
    }

    //Membuat hidden data untuk keperluan perhitungan total dan total item
    $data[] = array("<span class='hide total'>$total</span><span class='hide totalitem'>$total_item</span>", "", "", "", "", "", "");
    
    $output = array("data" => $data);
    return response()->json($output);
  }

  public function store(Request $request)
  {
    $bahan_baku              = BahanBaku::where('kode_bahan_baku', '=', $request['kode'])->first();

    $detail 				         = new DPemakaian;
    $detail->id_pemakaian 	 = $request['idpemakaian'];
    $detail->kode_bahan_baku = $request['kode'];
    $detail->harga_beli 	   = $bahan_baku->harga_beli;
    $detail->jumlah 		     = 1;
    $detail->sub_total 		   = $bahan_baku->harga_beli;
    $detail->save();
  }

  public function update(Request $request, $id)
  {
    $nama_input        = "jumlah_".$id;
    $detail 	         = DPemakaian::find($id);
    $detail->jumlah    = $request[$nama_input];
    $detail->sub_total = $detail->harga_beli * $request[$nama_input];
    $detail->update();
  }

  public function destroy($id)
  {
    $detail = DPemakaian::find($id);
    $detail->delete();
  }
   
  public function loadForm($total)
  {
    $data = array
    (
      "totalrp"        => format_uang($total),
      "terbilang"      => ucwords(terbilang($total))." Rupiah"
    );
    return response()->json($data);
  }
}

resources/views/dpemakaian/bahan_baku.blade.php
<div class="modal" id="modal-bahan_baku" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
            <h3 class="modal-title">Cari Bahan Baku</h3>
         </div>
            
         <div class="modal-body">
            <table class="table table-striped tabel-bahan_baku">
               <thead>
                  <tr>
                     <th>Kode Bahan Baku</th>
                     <th>Nama Bahan Baku</th>
                     <th>Harga Beli</th>
                     <th>Stok</th>
                     <th>Aksi</th>
                  </tr>
               </thead>
               <tbody>
                  @foreach($bahan_baku as $data)
                     <tr>
                        <th>{{ $data->kode_bahan_baku }}</th>
                        <th>{{ $data->nama_bahan_baku }}</th>
                        <th>Rp. {{ format_uang($data->harga_beli) }}</th>
                        <th>{{ $data->stok}}</th>
                        @if($data->stok > 0)
                           <th><a onclick="selectItem({{ $data->kode_bahan_baku }})" class="btn btn-primary"><i class="fa fa-check-circle"></i> Pilih</a></th>
                        @else
                           <th><a class="btn btn-primary"><i class="fa fa-check-circle"></i> Pilih</a></th>
                        @endif
                     </tr>
                  @endforeach
               </tbody>
            </table>
         </div>
      
      </div>
   </div>
</div>

resources/views/dpemakaian/index.blade.php
@extends('layouts.app')

@section('title')
  Transaksi Pemakaian
@endsection

@section('breadcrumb')
  @parent
  <li>pemakaian</li>
  <li>tambah</li>
@endsection

@section('content')     
  <div class="row">
    <div class="col-xs-12"> 
      <div class="box">
     
        <div class="box-body">
          <table>
            <tr><td width="150">Kode Karyawan</td><td><b>{{ $karyawan->kode_karyawan }}</b></td></tr>
            <tr><td width="150">Nama Karyawan</td><td><b>{{ $karyawan->nama }}</b></td></tr>
            <tr><td>Alamat</td><td><b>{{ $karyawan->alamat }}</b></td></tr>
            <tr><td>Telpon</td><td><b>{{ $karyawan->telpon }}</b></td></tr>
          </table>
          <hr>
          <form class="form form-horizontal form-bahan_baku" method="post">
          {{ csrf_field() }}  
            <input type="hidden" name="idpemakaian" value="{{ $idpemakaian }}">
            <div class="form-group">
              <label for="kode" class="col-md-2 control-label">Kode Bahan Baku</label>
              <div class="col-md-5">
                <div class="input-group">
                  <input id="kode" type="text" maxlength="5" class="form-control" name="kode" autofocus required>
                  <span class="input-group-btn">
                    <button onclick="showBahanBaku()" type="button" class="btn btn-info">...</button>
                  </span>
                </div>
              </div>
            </div>
          </form>
          <form class="form-keranjang">
          {{ csrf_field() }} {{ method_field('PATCH') }}
            <table class="table table-striped tabel-pemakaian">
              <thead>
                <tr>
                  <th width="30">No</th>
                  <th>Kode Bahan Baku</th>
                  <th>Nama Bahan Baku</th>
                  <th align="right">Harga Beli</th>
                  <th>Jumlah</th>
                  <th align="right">Sub Total</th>
                  <th width="100">Aksi</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </form>
          <div class="col-md-8">
             <div id="tampil-total" style="background: #dd4b39; color: #fff; font-size: 80px; text-align: center; height: 120px"></div>
             <div id="tampil-terbilang" style="background: #3c8dbc; color: #fff; font-size: 25px; padding: 10px"></div>
          </div>
          <div class="col-md-4">
            <form class="form form-horizontal form-pemakaian" method="post" action="{{  route('pemakaian.store') }} ">
            {{ csrf_field() }}
              <input type="hidden" name="idpemakaian" value="{{ $idpemakaian }}">
              <input type="hidden" name="total" id="total">
              <input type="hidden" name="totalitem" id="totalitem">

              <div class="form-group">
                <label for="totalrp" class="col-md-4 control-label">Total Harga</label>
                <div class="col-md-8">
                  <input type="text" class="form-control" id="totalrp" readonly>
                </div>
              </div>
            </form>
          </div>
        </div>
        
        <div class="box-footer">
          <button type="submit" class="btn btn-primary pull-right simpan"><i class="fa fa-floppy-o"></i> Simpan Transaksi</button>
        </div>

      </div>
    </div>
  </div>
  @include('dpemakaian.bahan_baku')
@endsection

@section('script')
  <script type="text/javascript">
  var table;
  $(function(){

    //Menampilkan data dengan plugin DataTable
    $('.tabel-bahan_baku').DataTable();

    //Menampilkan data dengan plugin DataTable
    table = $('.tabel-pemakaian').DataTable({
      "dom"        : 'Brt',
      "bSort"      : false,
      "processing" : true,
      "ajax"       : 
      {
        "url"      : "{{ route('dpemakaian.data', $idpemakaian) }}",
        "type"     : "GET"
      }
    }).on('draw.dt', function(){
      //Menjalankan fungsi loadForm() setiap tabel di reload
      loadForm($(this.target).val());
    });

    $('.form-bahan_baku').on('submit', function(){
      return false;
    });

    $('#kode').change(function(){
      addItem();
    });

    $('.form-keranjang').submit(function(){
      return false;
    });

    $('.simpan').click(function(){
      $('.form-pemakaian').submit();
    });

  });

  //Tambah Bahan Baku
  function addItem()
  {
    $.ajax({
      url     : "{{ route('dpemakaian.store') }}",
      type    : "POST",
      data    : $('.form-bahan_baku').serialize(),
      success : function(data)
      {
        $('#kode').val('').focus(); 
        table.ajax.reload(function(){
          loadForm($(this.target).val());
        });            
      },
      error   : function()
      {
        swal("Tidak dapat menyimpan data!", "", "warning");
      }   
    });
  }

  function showBahanBaku()
  {
    $('#modal-bahan_baku').modal('show');
  }

  function selectItem(kode)
  {
    $('#kode').val(kode);
    $('#modal-bahan_baku').modal('hide');
    addItem();
  }

  function changeCount(id)
  {
    $.ajax({
      url     : "dpemakaian/"+id,
      type    : "POST",
      data    : $('.form-keranjang').serialize(),
      success : function(data)
      {
        $('#kode').focus(); 
        table.ajax.reload(function(){
          loadForm($(this.target).val());
        });            
      },
      error   : function()
      {
        swal("Tidak dapat menyimpan data!", "","warning");
      }   
    });
  }

  //Hapus Bahan Baku
  function deleteItem(id)
  {
    swal({
      title               : "Anda Yakin?",
      text                : "Hapus Bahan Baku?",
      icon                : "warning",
      showCancelButton    : true,
      confirmButtonColor  : "DD6B55",
      confirmButtonText   : "YA, Hapus",
      closeOnConfirm      : false
    }, 
    function(isConfirm)
    {
      if (!isConfirm) return;
      $.ajax({
        url   : "dpemakaian/"+id,
        type  : "POST",
        data  : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
        success: function (data) 
        {
          swal("Berhasil!", "Bahan Baku berhasil dihapus!", "success");
          table.ajax.reload(function(){
            loadForm($(this.target).val());
          });
        },
        error: function (xhr, ajaxOptions, thrownError) 
        {
          swal("Gagal Menghapus!", "Silahkan coba lagi!", "error");
        }
      });
    });
  }

  function loadForm()
  {
    $('#total').val($('.total').text());
    $('#totalitem').val($('.totalitem').text());
    $.ajax({
      url      : "dpemakaian/loadform/"+$('#total').val(),
      type     : "GET",
      dataType : 'JSON',
      success  : function(data)
      {
        $('#totalrp').val("Rp. "+data.totalrp);
        $('#tampil-total').html("<small>Total :</small> Rp. "+data.totalrp);
        $('#tampil-terbilang').text(data.terbilang);
      },
      error    : function()
      {
        swal("Tidak dapat menampilkan data!","", "warning");
      }
    });
  }
  </script>
@endsection