routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\StockEmail;
use Illuminate\Support\Facades\Mail;

Route::get('/', 'HomeController@index')->name('home');


Auth::routes();


Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
   Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
   Route::resource('kategori', 'KategoriController');

   Route::get('bahan_baku/data', 'BahanBakuController@listData')->name('bahan_baku.data');
   Route::post('bahan_baku/hapus', 'BahanBakuController@deleteSelected');
   Route::resource('bahan_baku', 'BahanBakuController');
   Route::get('bahan_baku/lbahanbaku', 'BahanBakuController@show');

   Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
   Route::resource('supplier', 'SupplierController');

   Route::get('karyawan/data', 'KaryawanController@listData')->name('karyawan.data');
   Route::resource('karyawan', 'KaryawanController');

   Route::get('jenis_pengeluaran/data', 'JenisPengeluaranController@listData')->name('jenis_pengeluaran.data');
   Route::resource('jenis_pengeluaran', 'JenisPengeluaranController');

   Route::get('pembelian/data', 'PembelianController@listData')->name('pembelian.data');
   Route::get('pembelian/{id}/tambah', 'PembelianController@create');
   Route::get('pembelian/{id}/lihat', 'PembelianController@show');
   Route::resource('pembelian', 'PembelianController');

   Route::get('dpembelian/{id}/data', 'DPembelianController@listData')->name('dpembelian.data');
   Route::get('dpembelian/loadform/{diskon}/{total}', 'DPembelianController@loadForm');
   Route::resource('dpembelian', 'DPembelianController'); 

   Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
   Route::get('pengeluaran/{id}/tambah', 'PengeluaranController@create');
   Route::get('pengeluaran/{id}/lihat', 'PengeluaranController@show');
   Route::resource('pengeluaran', 'PengeluaranController');

   Route::get('dpengeluaran/{id}/data', 'DPengeluaranController@listData')->name('dpengeluaran.data');
   Route::get('dpengeluaran/loadform/{total}', 'DPengeluaranController@loadForm');
   Route::resource('dpengeluaran', 'DPengeluaranController'); 

   Route::get('pemakaian/data', 'PemakaianController@listData')->name('pemakaian.data');
   Route::get('pemakaian/{id}/tambah', 'PemakaianController@create');
   Route::get('pemakaian/{id}/lihat', 'PemakaianController@show');
   Route::resource('pemakaian', 'PemakaianController');

   Route::get('dpemakaian/{id}/data', 'DPemakaianController@listData')->name('dpemakaian.data');
   Route::get('dpemakaian/loadform/{total}', 'DPemakaianController@loadForm');
   Route::resource('dpemakaian', 'DPemakaianController'); 

   Route::get('laporan', 'LaporanController@index')->name('laporan.index');
   Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
   Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data'); 
   Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

   Route::get('lpembelian', 'LPembelianController@index')->name('lpembelian.index');
   Route::post('lpembelian', 'LPembelianController@refresh')->name('lpembelian.refresh');
   Route::get('lpembelian/data/{awal}/{akhir}', 'LPembelianController@listData')->name('lpembelian.data'); 
   Route::get('lpembelian/pdf/{awal}/{akhir}', 'LPembelianController@exportPDF');

   Route::get('lpengeluaran', 'LPengeluaranController@index')->name('lpengeluaran.index');
   Route::post('lpengeluaran', 'LPengeluaranController@refresh')->name('lpengeluaran.refresh');
   Route::get('lpengeluaran/data/{awal}/{akhir}', 'LPengeluaranController@listData')->name('lpengeluaran.data'); 
   Route::get('lpengeluaran/pdf/{awal}/{akhir}', 'LPengeluaranController@exportPDF');

   Route::get('lpemakaian', 'LPemakaianController@index')->name('lpemakaian.index');
   Route::post('lpemakaian', 'LPemakaianController@refresh')->name('lpemakaian.refresh');
   Route::get('lpemakaian/data/{awal}/{akhir}', 'LPemakaianController@listData')->name('lpemakaian.data'); 
   Route::get('lpemakaian/pdf/{awal}/{akhir}', 'LPemakaianController@exportPDF');

   Route::get('user/data', 'UserController@listData')->name('user.data');
   Route::get('user/profil', 'UserController@profil')->name('user.profil');
   Route::patch('user/{id}/change', 'UserController@changeProfil');
   Route::resource('user', 'UserController');

   Route::resource('setting', 'SettingController');

   //email
   Route::get('/email', function() {
      return view('send_email');
   });

   Route::get('/kirimemail',function(){
      Mail::to('luluk.9456@students.amikom.ac.id')->send(new StockEmail());
   });

   Route::post('/sendEmail', 'Email@sendEmail');
});


Route::group(['middleware' => 'web'], function(){
   Route::get('user/profil', 'UserController@profil')->name('user.profil');
   Route::patch('user/{id}/change', 'UserController@changeProfil');

   Route::get('laporan', 'LaporanController@index')->name('laporan.index');
   Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
   Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data'); 
   Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

   Route::get('lpembelian', 'LPembelianController@index')->name('lpembelian.index');
   Route::post('lpembelian', 'LPembelianController@refresh')->name('lpembelian.refresh');
   Route::get('lpembelian/data/{awal}/{akhir}', 'LPembelianController@listData')->name('lpembelian.data'); 
   Route::get('lpembelian/pdf/{awal}/{akhir}', 'LPembelianController@exportPDF');

   Route::get('lpengeluaran', 'LPengeluaranController@index')->name('lpengeluaran.index');
   Route::post('lpengeluaran', 'LPengeluaranController@refresh')->name('lpengeluaran.refresh');
   Route::get('lpengeluaran/data/{awal}/{akhir}', 'LPengeluaranController@listData')->name('lpengeluaran.data'); 
   Route::get('lpengeluaran/pdf/{awal}/{akhir}', 'LPengeluaranController@exportPDF');

   Route::get('lpemakaian', 'LPemakaianController@index')->name('lpemakaian.index');
   Route::post('lpemakaian', 'LPemakaianController@refresh')->name('lpemakaian.refresh');
   Route::get('lpemakaian/data/{awal}/{akhir}', 'LPemakaianController@listData')->name('lpemakaian.data'); 
   Route::get('lpemakaian/pdf/{awal}/{akhir}', 'LPemakaianController@exportPDF');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;
use Hash;

class UserController extends Controller
{
  //Fungsi Utama
	public function index()
  {
    return view('user.index'); 
  }
	
  //Fungsi yang akan dipanggil setelah index
  public function listData()
  {
    $user = User::where('level', '!=', 1)->orderBy('id', 'desc')->get();
    $no   = 0;
    $data = array();
    foreach($user as $list)
    {
      $no ++;
      $row    = array();
      $row[]  = $no;
      $row[]  = $list->name;
      $row[]  = $list->email;
      $row[]  = $list->telpon;
      $row[]  = '<div class="btn-group">
               		<a onclick="editForm('.$list->id.')" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
               		<a onclick="deleteData('.$list->id.')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                 </div>';
      $data[] = $row;
    }
    $output   = array("data" => $data);
    return response()->json($output);
  }
	
  public function store(Request $request)
  {
    $jml = User::where('email', '=', $request['email'])->count();

    if($jml < 1)
    {
      $user 			    = new User;
      $user->name 	  = $request['nama'];
      $user->email 	  = $request['email'];
      $user->password = bcrypt($request['password']);
      $user->telpon 	= $request['telpon'];
      $user->level 	  = 2;
      $user->foto 	  = "user.png";
      $user->save();
      echo json_encode(array('msg'=>'success'));
    }
    else
    {
      echo json_encode(array('msg'=>'error'));
    }
  }

  public function edit($id)
  {
    $user = User::find($id);
    echo json_encode($user);
  }

  public function update(Request $request, $id)
  {
    $user 										                       = User::find($id);
    $user->name 									                   = $request['nama'];
    $user->email 									                   = $request['email'];
    if(!empty($request['password'])) $user->password = bcrypt($request['password']);
    $user->telpon                                    = $request['telpon'];
    $user->update();
  }

  public function destroy($id)
  {
    $user = User::find($id);
    $user->delete();
  }

  public function profil()
  {
    $user = Auth::user();
    return view('user.profil', compact('user')); 
  }

  public function changeProfil(Request $request, $id)
  {
    $msg 			 = "succcess";
    $user 		 = User::find($id);
    //Cek apakah password tidak kosong
    if(!empty($request['password']))
    {
    	//Cek apakah password lama sama dengan DB
      if(Hash::check($request['passwordlama'], $user->password))
      {
        $user->password = bcrypt($request['password']);
      }
      else
      {
        $msg = 'error';
      }
    } 

    //Cek apakah input foto tidak kosong
    if ($request->hasFile('foto')) 
    {
      $file 		   = $request->file('foto');
      $nama_gambar = "fotouser_".$id.".".$file->getClientOriginalExtension();
      $lokasi 	   = public_path('images');
			 
			//Upload foto ke folder image
        $file->move($lokasi, $nama_gambar);
        $user->foto        = $nama_gambar;  
         
        $datagambar        = $nama_gambar;
    }
    else
    {
      $datagambar          = $user->foto; 
    }
    $user->update();
    echo json_encode(array('msg'=>$msg, 'url'=> asset('public/images/'.$datagambar))); 
  }
}

resources/views/user/form.blade.php
<div class="modal" id="modal-form" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
         <form class="form-horizontal" data-toggle="validator" method="post">
         {{ csrf_field() }} {{ method_field('POST') }}
         
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
               <h3 class="modal-title"></h3>
            </div>
                     
            <div class="modal-body">
               <input type="hidden" id="id" name="id">
               <div class="form-group">
                  <label for="nama" class="col-md-3 control-label">Nama User</label>
                  <div class="col-md-6">
                     <input id="nama" type="text" maxlength="30" class="form-control" name="nama" autofocus required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
               <div class="form-group">
                  <label for="email" class="col-md-3 control-label">Email</label>
                  <div class="col-md-6">
                     <input id="email" type="email" maxlength="50" class="form-control" name="email" required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
               <div class="form-group">
                  <label for="password" class="col-md-3 control-label">Password</label>
                  <div class="col-md-6">
                     <input id="password" type="password" maxlength="10" class="form-control" name="password" required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
               <div class="form-group">
                  <label for="password1" class="col-md-3 control-label">Ulang Password</label>
                  <div class="col-md-6">
                     <input id="password1" type="password" maxlength="10" class="form-control" data-match="#password" name="password1" required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
               <div class="form-group">
                  <label for="telpon" class="col-md-3 control-label">Telpon</label>
                  <div class="col-md-6">
                     <input id="telpon" type="text" maxlength="12" onkeypress="return hanyaAngka(event, false)" class="form-control" name="telpon" required>
                     <span class="help-block with-errors"></span>
                  </div>
               </div>
            </div>
            
            <div class="modal-footer">
               <button type="submit" class="btn btn-primary btn-save"><i class="fa fa-floppy-o"></i> Simpan </button>
               <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-arrow-circle-left"></i> Batal</button>
            </div>
            
         </form>

      </div>
    </div>
</div>

<script language="javascript">
  function hanyaAngka(e, decimal) 
  {
      var key;
      var keychar;
    
      if(window.event) 
      {
         key   = window.event.keyCode;
      } 
      else if(e) 
      {
         key = e.which;
      } 
      else return true;
   
      keychar = String.fromCharCode(key);
      if( (key==null) || (key==0) || (key==8) ||  (key==9) || (key==13) || (key==27) ) 
      {
         return true;
      } 
      else if ( (("0123456789").indexOf(keychar) > -1) ) 
      {
         return true;
      }  
      else if(decimal && (keychar == ".")) 
      {
         return true;
      } 
      else return false;
   }
</script>

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar User
@endsection

@section('breadcrumb')
  @parent
  <li>admin_gudang</li>
@endsection

@section('content')     
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <a onclick="addForm()" class="btn btn-success"><i class="fa fa-plus-circle"></i> Tambah</a>
        </div>

        <div class="box-body">  
          <table class="table table-striped">
            <thead>
              <tr>
                <th width="30">No</th>
                <th>Nama User</th>
                <th>Email</th>
                <th>Telpon</th>
                <th width="100">Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
  @include('user.form')
@endsection

@section('script')
  <script type="text/javascript">
    var table, save_method;
    $(function(){

      //Menampilkan data dengan plugin DataTable
      table = $('.table').DataTable({
        "processing" : true,
        "ajax"       : 
        {
          "url"      : "{{ route('user.data') }}",
          "type"     : "GET"
        }
      }); 
       
      //Menyimpan data form tambah/edit beserta validasinya
      $('#modal-form form').on('submit', function(e){
        if(!e.isDefaultPrevented()){
          var id                       = $('#id').val();
          if(save_method == "add") url = "{{ route('user.store') }}";
          else url                     = "user/"+id;
             
            $.ajax({
              url     : url,
              type    : "POST",
              data    : $('#modal-form form').serialize(),
              dataType: 'JSON',
              success : function(data)
              {
                if(data.msg=="error")
                {
                  swal("Email sudah terdaftar!", "", "warning");
                  $('#email').focus().select();
                }
                else
                {
                  swal("User Berhasil Disimpan!", "", "success");
                  $('#modal-form').modal('hide');
                  table.ajax.reload();
                }
              },
              error   : function()
              {
                swal("Tidak dapat menyimpan data!", "", "warning");
              }   
            });
          return false;
        }
      });
    });

    //Menampilkan form tambah
    function addForm()
    {
      save_method = "add";
      $('input[name=_method]').val('POST');
      $('#modal-form').modal('show');
      $('#modal-form form')[0].reset();            
      $('.modal-title').text('Tambah User');
      $('#password, #password1').attr('required', true);
    }

    //Menampilkan form edit dan menampilkan data pada form tersebut
    function editForm(id)
    {
      save_method = "edit";
      $('input[name=_method]').val('PATCH');
      $('#modal-form form')[0].reset();
      $.ajax({
        url      : "user/"+id+"/edit",
        type     : "GET",
        dataType : "JSON",
        success  : function(data)
        {
          $('#modal-form').modal('show');
          $('.modal-title').text('Edit User');
           
          $('#id').val(data.id);
          $('#nama').val(data.name);
          $('#email').val(data.email);
          $('#password, #password1').removeAttr('required');
          $('#telpon').val(data.telpon);
        },
        error    : function()
        {
           swal("Tidak dapat menampilkan data!", "", "warning");
        }
      });
    }

    //Menghapus Data
  function deleteData(id)
  {
    swal({
      title               : "Anda Yakin?",
      text                : "Hapus User?",
      icon                : "warning",
      showCancelButton    : true,
      confirmButtonColor  : "DD6B55",
      confirmButtonText   : "YA, Hapus",
      closeOnConfirm      : false
    }, 
    function(isConfirm)
    {
      if (!isConfirm) return;
      $.ajax({
        url   : "user/"+id,
        type  : "POST",
        data  : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
        success: function (data) 
        {
          swal("Berhasil!", "User berhasil dihapus!", "success");
          table.ajax.reload();
        },
        error: function (xhr, ajaxOptions, thrownError) 
        {
          swal("Gagal Menghapus!", "Silahkan coba lagi!", "error");
        }
      });
    });
  }
  </script>
@endsection

resources/views/user/profil.blade.php
@extends('layouts.app')

@section('title')
  Edit Profil
@endsection

@section('breadcrumb')
  @parent
  <li>user</li>
  <li>edit_profil</li>
@endsection

@section('content')     
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <form class="form form-horizontal" data-toggle="validator" method="post" enctype="multipart/form-data">
        {{ csrf_field() }} {{ method_field('PATCH') }}
       
          <div class="box-body">
            <div class="alert alert-info alert-dismissible" style="display:none">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <i class="icon fa fa-check"></i>
              Perubahan berhasil disimpan.
            </div>
            <div class="form-group">
              <label for="foto" class="col-md-2 control-label">Foto Profil</label>
              <div class="col-md-4">
                <input id="foto" type="file" class="form-control" name="foto">
                <br><div class="tampil-foto"> <img src="{{ asset('public/images/'.Auth::user()->foto) }}" width="200"></div>
              </div>
            </div>
            <div class="form-group">
              <label for="emailbaru" class="col-md-2 control-label">Email</label>
              <div class="col-md-6">
                <input id="emailbaru" type="email" maxlength="50" class="form-control" name="emailbaru">
                <span class="help-block with-errors"></span>
              </div>
            </div>
            <div class="form-group">
              <label for="passwordlama" class="col-md-2 control-label">Password Lama</label>
              <div class="col-md-6">
                <input id="passwordlama" type="password" maxlength="10" class="form-control" name="passwordlama">
                <span class="help-block with-errors"></span>
              </div>
            </div>
            <div class="form-group">
              <label for="password" class="col-md-2 control-label">Password Baru</label>
              <div class="col-md-6">
                <input id="password" type="password" maxlength="10" class="form-control" name="password">
                <span class="help-block with-errors"></span>
              </div>
            </div>
            <div class="form-group">
              <label for="password1" class="col-md-2 control-label">Ulang Password</label>
              <div class="col-md-6">
                <input id="password1" type="password" maxlength="10" class="form-control" data-match="#password" name="password1">
                <span class="help-block with-errors"></span>
              </div>
            </div>
            <div class="form-group">
              <label for="telponbaru" class="col-md-2 control-label">Telpon</label>
              <div class="col-md-6">
                <input id="telponbaru" type="text" maxlength="12" onkeypress="return hanyaAngka(event, false)" class="form-control" name="telponbaru">
                <span class="help-block with-errors"></span>
              </div>
            </div>
          </div>

          <div class="box-footer">
            <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-floppy-o"></i> Simpan Perubahan</button>
          </div>

        </form>

      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
  $(function(){
    //Saat password lama diubah
    $('#passwordlama').keyup(function(){
      if($(this).val() != "") $('#password, #password1').attr('required', true);
      else $('#password, #password1').attr('required', false);
    });

    $('.form').on('submit', function(e){
      if(!e.isDefaultPrevented())
      { 
        //Upload file via ajax
        $.ajax({
          url         : "{{ Auth::user()->id }}/change",
          type        : "POST",
          data        : new FormData($(".form")[0]),
          dataType    : 'JSON',
          async       : false,
          processData : false,
          contentType : false,
          success     : function(data)
          {
            //Tampilkan pesan jika data msg=error
            if(data.msg == "error")
            {
              swal("Password lama salah!", "", "warning");
              $('#passwordlama').focus().select();
            }
            else
            {
              d = new Date();
              $('.alert').css('display', 'block').delay(2000).fadeOut();
              //Update foto user
              $('.tampil-foto img, .user-image, .user-header img').attr('src', data.url+'?'+d.getTime());
            }
          },
          error       : function()
          {
            swal("Tidak dapat menyimpan data!", "", "warning");
          }   
        });
        return false;
      }
    });

  });

  function hanyaAngka(e, decimal) 
  {
      var key;
      var keychar;
    
      if(window.event) 
      {
         key   = window.event.keyCode;
      } 
      else if(e) 
      {
         key = e.which;
      } 
      else return true;
   
      keychar = String.fromCharCode(key);
      if( (key==null) || (key==0) || (key==8) ||  (key==9) || (key==13) || (key==27) ) 
      {
         return true;
      } 
      else if ( (("0123456789").indexOf(keychar) > -1) ) 
      {
         return true;
      }  
      else if(decimal && (keychar == ".")) 
      {
         return true;
      } 
      else return false;
   }
  </script>
@endsection